"""Index page generation — builds auto-maintained .md index files."""

from __future__ import annotations

import sqlite3
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

from hyperresearch.models.note import slugify

if TYPE_CHECKING:
    # Delta vs upstream: annotation-only Vault import (strict-mypy); upstream
    # left the constructor parameter unannotated. No runtime import cycle —
    # vault imports nothing from indexgen.
    from hyperresearch.core.vault import Vault


def _flat(text: str | None) -> str:
    """Neutralize free text for embedding in a generated markdown LINE.

    P1-7 remediation (D5): titles/summaries/tags arrive from note frontmatter
    and are attacker-influenceable; a raw newline would start its own bullet
    or heading inside an auto-maintained page. Whitespace of every kind
    collapses to single spaces, which is also what the note's own slugified
    id already assumes about titles.
    """
    return " ".join((text or "").split())


def _yaml_scalar(text: str | None) -> str:
    """Escape free text for embedding inside a double-quoted YAML scalar.

    P1-7 remediation (D5): the frontmatter here is hand-f stringed, so a
    literal `"` in a title/tag closed the quote early and corrupted the file
    for every parser. Backslash first, then quotes; newlines are gone via
    _flat.
    """
    return _flat(text).replace("\\", "\\\\").replace('"', '\\"')


def _tag_slug(tag: str) -> str:
    """Filename-safe slug for a tag — the same rules as note IDs.

    P1-7 remediation (D4): `ml/theory` used to become `_tag-ml/theory.md`,
    a nested path whose parent never exists — crashing build_all AFTER it had
    unlinked every existing index page (a vault left indexless). slugify maps
    '/' onto nothing (like it does inside note ids) and guarantees a
    non-empty, flat, length-capped filename.
    """
    return slugify(tag)


class IndexGenerator:
    def __init__(self, vault: Vault) -> None:
        self.vault = vault
        self.index_dir = vault.index_dir
        self.index_dir.mkdir(exist_ok=True)
        # Pages rendered during the current build pass: filename -> content.
        # P1-7 remediation (D4): rendering happens entirely before any disk
        # mutation so a failure can never leave the vault indexless.
        self._staged: dict[str, str] = {}

    def build_all(self) -> list[str]:
        """Build all index pages. Cleans up stale pages last, not first.

        P1-7 remediation (D4) crash-safety order:
          1. RENDER every page into memory (DB reads + string building only).
          2. Unlink stale pages that the new generation does NOT contain —
             pages being replaced are overwritten in place, never unlinked.
          3. Write the new generation.
        A failure in phase 1 leaves the previous generation byte-identical;
        the old unlink-first order destroyed it before the replacement existed.
        """
        self._staged = {}
        built: list[str] = []
        built.append(self._build_master_index())
        built.append(self._build_tags_index())
        built.extend(self._build_per_tag_indexes())
        built.append(self._build_recent())
        built.append(self._build_orphans())
        built.append(self._build_stats())
        built.append(self._build_raw_pending())
        built.extend(self._build_by_month())
        built.append(self._build_stale())
        built.append(self._build_most_linked())

        fresh = set(self._staged)
        if self.index_dir.exists():
            for old_file in self.index_dir.glob("*.md"):
                if old_file.name not in fresh:
                    old_file.unlink()
        for filename, content in self._staged.items():
            (self.index_dir / filename).write_text(content, encoding="utf-8")
        return [b for b in built if b]

    def _stage(self, filename: str, title: str, body: str) -> str:
        """Render one page into memory. Returns its index-relative path."""
        now_iso = datetime.now(UTC).isoformat()
        content = (
            f"---\n"
            f"title: \"{_yaml_scalar(title)}\"\n"
            f"id: \"{_yaml_scalar(filename.replace('.md', ''))}\"\n"
            f"type: index\n"
            f"created: {now_iso}\n"
            f"updated: {now_iso}\n"
            f"---\n\n"
            f"{body}\n\n"
            f"---\n*Auto-generated by hyperresearch. Do not edit manually.*\n"
        )
        self._staged[filename] = content
        return f"index/{filename}"

    def _build_master_index(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, path, status, type, parent, word_count, summary "
            "FROM notes WHERE type NOT IN ('index') ORDER BY parent, title"
        ).fetchall()

        lines = ["# Master Index\n", f"**{len(rows)}** notes in vault.\n"]

        # Group by parent
        groups: dict[str, list[sqlite3.Row]] = {}
        for r in rows:
            parent = _flat(r["parent"]) or "Uncategorized"
            groups.setdefault(parent, []).append(r)

        for parent, notes in sorted(groups.items()):
            lines.append(f"\n## {parent}\n")
            for n in notes:
                status_badge = f"`{n['status']}`"
                summary = f" — {_flat(n['summary'])}" if n["summary"] else ""
                title = _flat(n["title"])
                lines.append(f"- [[{n['id']}]] — {title}{summary} {status_badge} ({n['word_count']} words)")

        return self._stage("_index.md", "Master Index", "\n".join(lines))

    def _build_tags_index(self) -> str:
        rows = self.vault.db.execute(
            "SELECT tag, COUNT(*) as count FROM tags GROUP BY tag ORDER BY count DESC"
        ).fetchall()

        lines = ["# Tags Index\n", f"**{len(rows)}** unique tags.\n"]
        for r in rows:
            tag = _flat(r["tag"])
            # Only link to per-tag page if tag has 3+ notes (avoids index bloat)
            if r["count"] >= 3:
                lines.append(f"- **{tag}** ({r['count']} notes) → [[_tag-{_tag_slug(tag)}]]")
            else:
                lines.append(f"- **{tag}** ({r['count']} notes)")

        return self._stage("_tags.md", "Tags Index", "\n".join(lines))

    def _build_per_tag_indexes(self) -> list[str]:
        """Only generate per-tag index pages for tags with 3+ notes."""
        built: list[str] = []
        tags = self.vault.db.execute(
            "SELECT tag, COUNT(*) as c FROM tags GROUP BY tag HAVING c >= 3 ORDER BY tag"
        ).fetchall()
        for tag_row in tags:
            tag = _flat(tag_row["tag"])
            rows = self.vault.db.execute(
                "SELECT n.id, n.title, n.status, n.word_count, n.summary "
                "FROM notes n JOIN tags t ON n.id = t.note_id "
                "WHERE t.tag = ? ORDER BY n.title",
                (tag,),
            ).fetchall()
            lines = [f"# Tag: {tag}\n", f"**{len(rows)}** notes.\n"]
            for r in rows:
                summary = f" — {_flat(r['summary'])}" if r["summary"] else ""
                title = _flat(r["title"])
                lines.append(f"- [[{r['id']}]] — {title}{summary} `{r['status']}`")
            built.append(self._stage(f"_tag-{_tag_slug(tag)}.md", f"Tag: {tag}", "\n".join(lines)))
        return built

    def _build_recent(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, status, type, created, updated, word_count "
            "FROM notes WHERE type NOT IN ('index') "
            "ORDER BY COALESCE(updated, created) DESC LIMIT 50"
        ).fetchall()

        lines = ["# Recently Updated\n"]
        for r in rows:
            date = r["updated"] or r["created"]
            if date and len(date) > 10:
                date = date[:10]
            lines.append(f"- `{date}` [[{r['id']}]] — {_flat(r['title'])}")

        return self._stage("_recent.md", "Recently Updated", "\n".join(lines))

    def _build_orphans(self) -> str:
        rows = self.vault.db.execute("""
            SELECT n.id, n.title, n.path, n.status
            FROM notes n
            WHERE n.type NOT IN ('index', 'raw')
              AND n.id NOT IN (SELECT DISTINCT target_id FROM links WHERE target_id IS NOT NULL)
              AND n.id NOT IN (SELECT DISTINCT source_id FROM links)
            ORDER BY n.title
        """).fetchall()

        lines = ["# Orphan Notes\n", f"**{len(rows)}** notes with no inbound or outbound links.\n"]
        if not rows:
            lines.append("*No orphans — all notes are connected!*")
        for r in rows:
            lines.append(f"- [[{r['id']}]] — {_flat(r['title'])} ({r['path']})")

        return self._stage("_orphans.md", "Orphan Notes", "\n".join(lines))

    def _build_stats(self) -> str:
        total = self.vault.db.execute("SELECT COUNT(*) as c FROM notes").fetchone()["c"]
        total_words = self.vault.db.execute(
            "SELECT COALESCE(SUM(word_count), 0) as c FROM notes"
        ).fetchone()["c"]
        total_links = self.vault.db.execute("SELECT COUNT(*) as c FROM links").fetchone()["c"]
        broken = self.vault.db.execute(
            "SELECT COUNT(*) as c FROM links WHERE target_id IS NULL"
        ).fetchone()["c"]
        total_tags = self.vault.db.execute(
            "SELECT COUNT(DISTINCT tag) as c FROM tags"
        ).fetchone()["c"]

        by_status: dict[str, int] = {}
        for r in self.vault.db.execute("SELECT status, COUNT(*) as c FROM notes GROUP BY status"):
            by_status[r["status"]] = r["c"]

        by_type: dict[str, int] = {}
        for r in self.vault.db.execute("SELECT type, COUNT(*) as c FROM notes GROUP BY type"):
            by_type[r["type"]] = r["c"]

        lines = [
            "# Vault Statistics\n",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total notes | {total} |",
            f"| Total words | {total_words:,} |",
            f"| Unique tags | {total_tags} |",
            f"| Total links | {total_links} |",
            f"| Broken links | {broken} |",
            "",
            "## By Status\n",
        ]
        for s, c in sorted(by_status.items()):
            lines.append(f"- **{s}**: {c}")

        lines.append("\n## By Type\n")
        for t, c in sorted(by_type.items()):
            lines.append(f"- **{t}**: {c}")

        return self._stage("_stats.md", "Vault Statistics", "\n".join(lines))

    def _build_raw_pending(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, path, created FROM notes WHERE type = 'raw' ORDER BY created DESC"
        ).fetchall()

        lines = ["# Unprocessed (Pending Compilation)\n", f"**{len(rows)}** raw notes awaiting compilation.\n"]
        for r in rows:
            date = r["created"][:10] if r["created"] and len(r["created"]) > 10 else r["created"]
            lines.append(f"- `{date}` [[{r['id']}]] — {_flat(r['title'])}")

        return self._stage("_raw-pending.md", "Raw Pending", "\n".join(lines))

    def _build_by_month(self) -> list[str]:
        """Generate per-month index pages for months with 3+ notes."""
        rows = self.vault.db.execute(
            "SELECT id, title, status, summary, created FROM notes "
            "WHERE type NOT IN ('index') AND created IS NOT NULL "
            "ORDER BY created DESC"
        ).fetchall()

        months: dict[str, list[sqlite3.Row]] = {}
        for r in rows:
            created = r["created"] or ""
            month = created[:7] if len(created) >= 7 else "unknown"
            months.setdefault(month, []).append(r)

        built: list[str] = []
        for month, notes in sorted(months.items(), reverse=True):
            if len(notes) < 3 or month == "unknown":
                continue
            lines = [f"# Notes from {month}\n", f"**{len(notes)}** notes.\n"]
            for r in notes:
                date = (r["created"] or "")[:10]
                summary = f" — {_flat(r['summary'])}" if r["summary"] else ""
                lines.append(f"- `{date}` [[{r['id']}]] — {_flat(r['title'])}{summary}")
            built.append(self._stage(f"_month-{month}.md", f"Month: {month}", "\n".join(lines)))
        return built

    def _build_stale(self) -> str:
        """Evergreen notes not updated in 6+ months — candidates for review."""
        cutoff = (datetime.now(UTC) - timedelta(days=180)).isoformat()
        rows = self.vault.db.execute(
            "SELECT id, title, status, updated, created, word_count FROM notes "
            "WHERE status = 'evergreen' AND type NOT IN ('index') "
            "AND COALESCE(updated, created) < ? "
            "ORDER BY COALESCE(updated, created)",
            (cutoff,),
        ).fetchall()

        lines = ["# Stale Notes\n", f"**{len(rows)}** evergreen notes not updated in 6+ months.\n"]
        for r in rows:
            date = (r["updated"] or r["created"] or "")[:10]
            lines.append(f"- `{date}` [[{r['id']}]] — {_flat(r['title'])} ({r['word_count']}w)")

        return self._stage("_stale.md", "Stale Notes", "\n".join(lines))

    def _build_most_linked(self) -> str:
        """Top 30 notes by inbound link count."""
        rows = self.vault.db.execute(
            "SELECT l.target_id as id, n.title, COUNT(*) as inbound "
            "FROM links l JOIN notes n ON l.target_id = n.id "
            "WHERE l.target_id IS NOT NULL "
            "GROUP BY l.target_id ORDER BY inbound DESC LIMIT 30"
        ).fetchall()

        lines = ["# Most Linked Notes\n", f"Top {len(rows)} notes by inbound link count.\n"]
        for r in rows:
            lines.append(f"- [[{r['id']}]] — {_flat(r['title'])} ({r['inbound']} inbound links)")

        return self._stage("_most-linked.md", "Most Linked", "\n".join(lines))
