"""Smoke coverage for core index generation (hyperresearch/indexgen).

Delta vs upstream (P1-7): upstream ships NO tests for IndexGenerator
(grep-verified over the reference tests/ tree — its only consumers,
cli/{index,repair,watch}.py, are later pieces). These offline smoke tests
pin the module's engagement with OUR Vault (index_dir layout, page set,
stale-page cleanup) so the CLI piece inherits a proven base, mirroring the
P1-2 precedent of covering upstream-untested modules when they land.
"""

from __future__ import annotations

from hyperresearch.core.note import write_note
from hyperresearch.core.sync import compute_sync_plan, execute_sync
from hyperresearch.indexgen.generator import IndexGenerator

CORE_PAGES = (
    "_index.md", "_tags.md", "_recent.md", "_orphans.md",
    "_stats.md", "_raw-pending.md", "_stale.md", "_most-linked.md",
)


def _resync(vault) -> None:
    plan = compute_sync_plan(vault, force=True)
    execute_sync(vault, plan)


class TestBuildAll:
    def test_build_all_creates_core_pages(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        names = {b.split("/", 1)[1] for b in built}
        for page in CORE_PAGES:
            assert page in names, page
            assert (seeded_vault.index_dir / page).exists()

    def test_pages_carry_frontmatter_and_autogen_footer(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_index.md").read_text(encoding="utf-8")
        assert text.startswith('---\ntitle: "Master Index"\n')
        assert 'type: index\n' in text
        assert "*Auto-generated by hyperresearch. Do not edit manually.*\n" in text

    def test_build_all_removes_stale_pages(self, seeded_vault):
        stale = seeded_vault.index_dir / "_retired-page.md"
        seeded_vault.index_dir.mkdir(parents=True, exist_ok=True)
        stale.write_text("obsolete\n", encoding="utf-8")
        IndexGenerator(seeded_vault).build_all()
        assert not stale.exists()

    def test_returned_paths_are_index_relative(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        assert built and all(b.startswith("index/") for b in built)


class TestPageContents:
    def test_master_index_lists_notes_by_parent(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_index.md").read_text(encoding="utf-8")
        assert "[[python-async-patterns]]" in text
        assert "[[rust-ownership]]" in text
        assert "## python" in text and "## rust" in text

    def test_per_tag_indexes_only_for_tags_with_three_plus_notes(self, seeded_vault):
        # seeded_vault: only `concurrency` reaches 3 notes; python/rust have 1.
        built = IndexGenerator(seeded_vault).build_all()
        assert "index/_tag-concurrency.md" in built
        assert not any("_tag-python.md" in b for b in built)
        text = (seeded_vault.index_dir / "_tags.md").read_text(encoding="utf-8")
        assert "[[_tag-concurrency]]" in text  # linked only at 3+
        assert "**python** (" in text  # small tags stay bare lines

    def test_orphans_page_lists_unlinked_note(self, seeded_vault):
        # Re-sync so the freshly generated index notes don't count as orphans;
        # the seeded Orphan Note has no links in either direction.
        _resync(seeded_vault)
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_orphans.md").read_text(encoding="utf-8")
        assert "[[orphan-note]]" in text
        assert "No orphans" not in text

    def test_no_orphans_message_when_fully_connected(self, tmp_vault):
        write_note(
            tmp_vault.notes_dir,
            "Only Note",
            body="Links to [[self]] and back.\n",
            tags=["solo"],
        )
        _resync(tmp_vault)
        IndexGenerator(tmp_vault).build_all()
        text = (tmp_vault.index_dir / "_orphans.md").read_text(encoding="utf-8")
        assert "*No orphans — all notes are connected!*" in text

    def test_stats_page_tables(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_stats.md").read_text(encoding="utf-8")
        assert "| Metric | Value |" in text
        assert "| Total notes | 4 |" in text
        assert "| Unique tags | 7 |" in text
        assert "## By Status" in text and "## By Type" in text
        # Broken link: [[nonexistent-topic]] in the concurrency moc.
        assert "| Broken links | 1 |" in text

    def test_month_index_built_for_months_with_three_plus_notes(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        months = [b for b in built if b.startswith("index/_month-")]
        assert months, "all four seeded notes share one creation month"

    def test_most_linked_counts_inbound(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_most-linked.md").read_text(encoding="utf-8")
        # python-async-patterns is linked from rust-ownership and concurrency.
        assert "- [[python-async-patterns]]" in text
        assert "(2 inbound links)" in text
