"""Smoke coverage for core index generation (hyperresearch/indexgen).

Delta vs upstream (P1-7): upstream ships NO tests for IndexGenerator
(grep-verified over the reference tests/ tree — its only consumers,
cli/{index,repair,watch}.py, are later pieces). These offline smoke tests
pin the module's engagement with OUR Vault (index_dir layout, page set,
stale-page cleanup) so the CLI piece inherits a proven base, mirroring the
P1-2 precedent of covering upstream-untested modules when they land.

P1-7 remediation additions: TestTagSlugSafety + TestCrashSafeRebuild (D4)
and TestInterpolationEscaping (D5) — all failed against pre-fix code.

Critic-gap wave addition (H-1): TestHostileMonthKey — the month key in
`_month-{created[:7]}.md` was raw frontmatter `created`, so a hostile value
staged a path-separator filename that crashed the WRITE phase after build_all
had already unlinked every 'stale' page.
"""

from __future__ import annotations

import re

import pytest
import yaml

from hyperresearch.core.note import write_note
from hyperresearch.core.sync import compute_sync_plan, execute_sync
from hyperresearch.indexgen.generator import IndexGenerator

CORE_PAGES = (
    "_index.md", "_tags.md", "_recent.md", "_orphans.md",
    "_stats.md", "_raw-pending.md", "_stale.md", "_most-linked.md",
)


def _resync(vault) -> None:
    plan = compute_sync_plan(vault, force=True)
    execute_sync(vault, plan)


class TestBuildAll:
    def test_build_all_creates_core_pages(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        names = {b.split("/", 1)[1] for b in built}
        for page in CORE_PAGES:
            assert page in names, page
            assert (seeded_vault.index_dir / page).exists()

    def test_pages_carry_frontmatter_and_autogen_footer(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_index.md").read_text(encoding="utf-8")
        assert text.startswith('---\ntitle: "Master Index"\n')
        assert 'type: index\n' in text
        assert "*Auto-generated by hyperresearch. Do not edit manually.*\n" in text

    def test_build_all_removes_stale_pages(self, seeded_vault):
        stale = seeded_vault.index_dir / "_retired-page.md"
        seeded_vault.index_dir.mkdir(parents=True, exist_ok=True)
        stale.write_text("obsolete\n", encoding="utf-8")
        IndexGenerator(seeded_vault).build_all()
        assert not stale.exists()

    def test_returned_paths_are_index_relative(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        assert built and all(b.startswith("index/") for b in built)


class TestPageContents:
    def test_master_index_lists_notes_by_parent(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_index.md").read_text(encoding="utf-8")
        assert "[[python-async-patterns]]" in text
        assert "[[rust-ownership]]" in text
        assert "## python" in text and "## rust" in text

    def test_per_tag_indexes_only_for_tags_with_three_plus_notes(self, seeded_vault):
        # seeded_vault: only `concurrency` reaches 3 notes; python/rust have 1.
        built = IndexGenerator(seeded_vault).build_all()
        assert "index/_tag-concurrency.md" in built
        assert not any("_tag-python.md" in b for b in built)
        text = (seeded_vault.index_dir / "_tags.md").read_text(encoding="utf-8")
        assert "[[_tag-concurrency]]" in text  # linked only at 3+
        assert "**python** (" in text  # small tags stay bare lines

    def test_orphans_page_lists_unlinked_note(self, seeded_vault):
        # Re-sync so the freshly generated index notes don't count as orphans;
        # the seeded Orphan Note has no links in either direction.
        _resync(seeded_vault)
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_orphans.md").read_text(encoding="utf-8")
        assert "[[orphan-note]]" in text
        assert "No orphans" not in text

    def test_no_orphans_message_when_fully_connected(self, tmp_vault):
        write_note(
            tmp_vault.notes_dir,
            "Only Note",
            body="Links to [[self]] and back.\n",
            tags=["solo"],
        )
        _resync(tmp_vault)
        IndexGenerator(tmp_vault).build_all()
        text = (tmp_vault.index_dir / "_orphans.md").read_text(encoding="utf-8")
        assert "*No orphans — all notes are connected!*" in text

    def test_stats_page_tables(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_stats.md").read_text(encoding="utf-8")
        assert "| Metric | Value |" in text
        assert "| Total notes | 4 |" in text
        assert "| Unique tags | 7 |" in text
        assert "## By Status" in text and "## By Type" in text
        # Broken link: [[nonexistent-topic]] in the concurrency moc.
        assert "| Broken links | 1 |" in text

    def test_month_index_built_for_months_with_three_plus_notes(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        months = [b for b in built if b.startswith("index/_month-")]
        assert months, "all four seeded notes share one creation month"

    def test_most_linked_counts_inbound(self, seeded_vault):
        IndexGenerator(seeded_vault).build_all()
        text = (seeded_vault.index_dir / "_most-linked.md").read_text(encoding="utf-8")
        # python-async-patterns is linked from rust-ownership and concurrency.
        assert "- [[python-async-patterns]]" in text
        assert "(2 inbound links)" in text


def _three_tagged(tmp_vault, tag: str) -> None:
    for i in range(3):
        write_note(
            tmp_vault.notes_dir,
            f"{tag} Note {i}",
            body=f"Body {i} with [[anchor-{i}]].\n",
            tags=[tag],
        )
    _resync(tmp_vault)


class TestTagSlugSafety:
    """P1-7 remediation D4: a tag containing '/' crashed build_all by turning
    `_tag-{tag}.md` into a nested path whose parent does not exist."""

    def test_slash_tag_builds_safe_flat_page(self, tmp_vault):
        _three_tagged(tmp_vault, "ml/theory")
        built = IndexGenerator(tmp_vault).build_all()
        # Same slug rules as note IDs: 'ml/theory' -> 'mltheory'.
        assert "index/_tag-mltheory.md" in built
        page = tmp_vault.index_dir / "_tag-mltheory.md"
        assert page.exists(), "per-tag page must land as a flat file"
        tags_page = (tmp_vault.index_dir / "_tags.md").read_text(encoding="utf-8")
        assert "[[_tag-mltheory]]" in tags_page
        assert "_tag-ml/theory" not in tags_page, "unsanitized tag must not leak into links"

    def test_slash_tag_creates_no_nested_directory(self, tmp_vault):
        _three_tagged(tmp_vault, "ml/theory")
        IndexGenerator(tmp_vault).build_all()
        dirs = [p for p in tmp_vault.index_dir.iterdir() if p.is_dir()]
        assert dirs == [], f"index_dir must stay flat, got {dirs}"


class TestCrashSafeRebuild:
    """P1-7 remediation D4: build_all unlinked every existing index page
    BEFORE rendering the new ones, so any mid-build failure left the vault
    indexless. Pages must now be fully rendered before anything is removed,
    and surviving pages must never be unlinked at all."""

    def test_failed_render_keeps_previous_generation(self, seeded_vault, monkeypatch):
        IndexGenerator(seeded_vault).build_all()  # generation A on disk
        before = {
            page: (seeded_vault.index_dir / page).read_text(encoding="utf-8")
            for page in CORE_PAGES
        }

        def explode(self):
            raise RuntimeError("induced mid-build failure")

        monkeypatch.setattr(IndexGenerator, "_build_stats", explode)
        with pytest.raises(RuntimeError, match="induced"):
            IndexGenerator(seeded_vault).build_all()

        after = {
            page: (seeded_vault.index_dir / page).read_text(encoding="utf-8")
            for page in CORE_PAGES
        }
        assert before == after, "a failed rebuild must leave the old indexes untouched"

    def test_successful_rebuild_still_removes_stale_pages(self, seeded_vault):
        stale = seeded_vault.index_dir / "_retired-page.md"
        seeded_vault.index_dir.mkdir(parents=True, exist_ok=True)
        stale.write_text("obsolete\n", encoding="utf-8")
        IndexGenerator(seeded_vault).build_all()
        assert not stale.exists()


class TestInterpolationEscaping:
    """P1-7 remediation D5: titles/tags were interpolated raw into markdown
    bullets and double-quoted YAML scalars — a newline or quote corrupted the
    generated file's structure."""

    def test_multiline_title_flattened_in_markdown_and_yaml(self, tmp_vault):
        evil_title = "Real Title\ninjected: [oops](x)"
        write_note(
            tmp_vault.notes_dir,
            evil_title,
            body="Harmless body.\n",
            summary="one line summary",
        )
        _resync(tmp_vault)
        built = IndexGenerator(tmp_vault).build_all()
        assert built  # generation completed without crashing

        master = (tmp_vault.index_dir / "_index.md").read_text(encoding="utf-8")
        fm = yaml.safe_load(master.split("---\n")[1])
        # The PAGE's own frontmatter stays intact (constant title here; the
        # note-title-in-frontmatter surface is covered by the quote-tag test
        # below, whose per-tag page embeds the raw tag in its YAML title).
        assert "\n" not in fm["title"]
        assert fm["type"] == "index"

        # Body bullet stays one line: the flattened title lands on the note's
        # bullet, and the injected fragment never starts a line of its own.
        bullets = [
            line for line in master.splitlines() if "injected: [oops](x)" in line
        ]
        assert len(bullets) == 1, "flattened title must appear exactly once"
        assert bullets[0].startswith("- [["), "title fragment must not start its own line"
        assert "Real Title" in bullets[0]

    def test_quote_tag_yields_parseable_frontmatter(self, tmp_vault):
        _three_tagged(tmp_vault, 'say "hi"')
        IndexGenerator(tmp_vault).build_all()

        page = tmp_vault.index_dir / "_tag-say-hi.md"
        assert page.exists()
        data = yaml.safe_load(page.read_text(encoding="utf-8").split("---\n")[1])
        assert data["title"] == 'Tag: say "hi"'
        assert data["type"] == "index"

        tags_page = (tmp_vault.index_dir / "_tags.md").read_text(encoding="utf-8")
        assert yaml.safe_load(tags_page.split("---\n")[1])["title"] == "Tags Index"

    def test_newline_tag_is_slugified_and_neutralized(self, tmp_vault):
        _three_tagged(tmp_vault, "multi\nline")
        built = IndexGenerator(tmp_vault).build_all()
        # \n routes through slugify's whitespace rule -> 'multi-line'.
        assert "index/_tag-multi-line.md" in built
        for name in built:
            assert "/" not in name.removeprefix("index/"), name


class TestHostileMonthKey:
    """Critic-gap H-1: `_month-{created[:7]}.md` interpolated the raw
    frontmatter `created` string into a FILENAME. A hostile value like
    '../../pwn' staged fine (filenames were just dict keys during render),
    then crashed `write_text` with FileNotFoundError AFTER build_all had
    unlinked every page not in the fresh set — vault left indexless.

    The DB is the trust boundary here: sync validates `created` through the
    NoteMeta schema, but indexgen reads whatever sits in sqlite (external
    tools, migrations, hand edits), so these tests seed out-of-band UPDATEs.
    """

    def _seed_hostile_month(self, tmp_vault) -> None:
        for i in range(3):  # a month page only stages at 3+ notes
            write_note(tmp_vault.notes_dir, f"Hostile {i}", body=f"body {i}\n")
        _resync(tmp_vault)
        tmp_vault.db.execute("UPDATE notes SET created = '../../pwn'")
        tmp_vault.db.commit()

    def test_hostile_created_raises_before_touching_disk(self, tmp_vault):
        IndexGenerator(tmp_vault).build_all()  # generation A on disk
        before = {
            p.name: p.read_text(encoding="utf-8")
            for p in sorted(tmp_vault.index_dir.glob("*.md"))
        }

        self._seed_hostile_month(tmp_vault)

        with pytest.raises(ValueError, match="created"):
            IndexGenerator(tmp_vault).build_all()

        after = {
            p.name: p.read_text(encoding="utf-8")
            for p in sorted(tmp_vault.index_dir.glob("*.md"))
        }
        assert before == after, "a hostile month key must abort BEFORE unlink/write"
        assert before, "generation A must still be fully present"

    def test_happy_path_month_pages_unchanged(self, seeded_vault):
        built = IndexGenerator(seeded_vault).build_all()
        months = [b.removeprefix("index/") for b in built if "_month-" in b]
        assert months, "all four seeded notes share one creation month"
        for name in months:
            assert re.fullmatch(r"_month-\d{4}-\d{2}\.md", name), name
