"""P5 conditional template rendering (tests/test_core/test_repo_lane_render.py).

Covers the render half of the P5 piece, mirroring the P4-C structure in
tests/test_core/test_parallel_lane_render.py:

(a) DEFAULT-STATE BYTE IDENTITY — rendering with no repo_lane kwarg (or
    False) reproduces the frozen pre-P5 goldens EXACTLY, chain-wide;
(b) REPO LANE ON — the width-sweep skill gains EXACTLY ONE Lens-E
    paragraph, and every other skill stays byte-identical to its default
    golden;
(c) INDEPENDENCE — repo_lane=True does NOT inject the parallel sentence
    and parallel_lane=True does NOT inject the repo paragraph; both on
    injects both, once each;
(d) GUARD — a missing repo anchor is a renderer bug and must raise loudly;
(e) INSTALL THREADING — `hpr install` derives the flag from the vault's
    config.toml ([web] repo_source_lane OR the profile overlay): enabled
    bakes the paragraph, disabled leaves the skill byte-identical to the
    default golden.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest
from typer.testing import CliRunner

from hyperresearch.cli import app
from hyperresearch.core.opencode_skills import (
    _WIDTH_SWEEP_REPO_PARAGRAPH,
    SKILL_SPECS,
    render_skills,
)
from hyperresearch.core.profiles import resolve_profile

runner = CliRunner()

SKILL_GOLDENS_DIR = Path(__file__).parent.parent / "fixtures" / "skill_goldens"
REPO_LANE_ON_GOLDENS_DIR = (
    Path(__file__).parent.parent / "fixtures" / "skill_goldens_repo_lane_on"
)

PROFILE = resolve_profile("full")
AFFECTED_SKILL = "hyperresearch-2-width-sweep"


def _render(tmp_path: Path, *, repo_lane: bool, parallel_lane: bool = False) -> Path:
    name = "skills-both" if (repo_lane and parallel_lane) else (
        "skills-repo" if repo_lane else "skills-off"
    )
    skills_dir = tmp_path / name
    render_skills(skills_dir, PROFILE, parallel_lane=parallel_lane, repo_lane=repo_lane)
    return skills_dir


# ---------------------------------------------------------------------------
# (a) Default-state byte identity
# ---------------------------------------------------------------------------


def test_default_render_matches_frozen_goldens(tmp_path: Path) -> None:
    """No repo_lane kwarg -> byte-identical to the pre-P5 frozen goldens."""
    skills_dir = tmp_path / "skills-default"
    render_skills(skills_dir, PROFILE)
    for spec in SKILL_SPECS:
        golden = SKILL_GOLDENS_DIR / f"{spec.name}.md"
        assert golden.is_file(), f"missing golden {golden.name}"
        rendered = (skills_dir / spec.name / "SKILL.md").read_text(encoding="utf-8")
        assert rendered == golden.read_text(encoding="utf-8"), f"drift: {spec.name}"


def test_repo_lane_false_same_as_omitted(tmp_path: Path) -> None:
    a = _render(tmp_path / "a", repo_lane=False)
    b = tmp_path / "b" / "skills-default"
    render_skills(b, PROFILE, repo_lane=False)
    for spec in SKILL_SPECS:
        assert (
            (a / spec.name / "SKILL.md").read_text(encoding="utf-8")
            == (b / spec.name / "SKILL.md").read_text(encoding="utf-8")
        )


# ---------------------------------------------------------------------------
# (b) Repo lane on — paragraph lands, everything else untouched
# ---------------------------------------------------------------------------


def test_repo_lane_injects_paragraph_only_in_width_sweep(tmp_path: Path) -> None:
    skills_dir = _render(tmp_path, repo_lane=True)
    for spec in SKILL_SPECS:
        rendered = (skills_dir / spec.name / "SKILL.md").read_text(encoding="utf-8")
        if spec.name == AFFECTED_SKILL:
            assert rendered.count(_WIDTH_SWEEP_REPO_PARAGRAPH) == 1
        else:
            assert _WIDTH_SWEEP_REPO_PARAGRAPH not in rendered
            golden = SKILL_GOLDENS_DIR / f"{spec.name}.md"
            assert rendered == golden.read_text(encoding="utf-8"), f"drift: {spec.name}"


def test_repo_lane_golden_fixture_roundtrip(tmp_path: Path) -> None:
    """The frozen lane-on golden matches a fresh render byte-for-byte."""
    skills_dir = _render(tmp_path, repo_lane=True)
    golden = REPO_LANE_ON_GOLDENS_DIR / f"{AFFECTED_SKILL}.md"
    if golden.is_file():  # generated by the freeze script / first run
        rendered = (skills_dir / AFFECTED_SKILL / "SKILL.md").read_text(
            encoding="utf-8"
        )
        assert rendered == golden.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# (c) Independence of the two lane flags
# ---------------------------------------------------------------------------


def test_repo_lane_does_not_inject_parallel_sentence(tmp_path: Path) -> None:
    from hyperresearch.core.opencode_skills import _WIDTH_SWEEP_LANE_SENTENCE

    skills_dir = _render(tmp_path, repo_lane=True)
    rendered = (skills_dir / AFFECTED_SKILL / "SKILL.md").read_text(encoding="utf-8")
    assert _WIDTH_SWEEP_REPO_PARAGRAPH in rendered
    assert _WIDTH_SWEEP_LANE_SENTENCE not in rendered


def test_parallel_lane_does_not_inject_repo_paragraph(tmp_path: Path) -> None:
    skills_dir = _render(tmp_path, repo_lane=False, parallel_lane=True)
    rendered = (skills_dir / AFFECTED_SKILL / "SKILL.md").read_text(encoding="utf-8")
    from hyperresearch.core.opencode_skills import _WIDTH_SWEEP_LANE_SENTENCE

    assert _WIDTH_SWEEP_LANE_SENTENCE in rendered
    assert _WIDTH_SWEEP_REPO_PARAGRAPH not in rendered


def test_both_lanes_inject_both_sentences_once_each(tmp_path: Path) -> None:
    from hyperresearch.core.opencode_skills import _WIDTH_SWEEP_LANE_SENTENCE

    skills_dir = _render(tmp_path, repo_lane=True, parallel_lane=True)
    rendered = (skills_dir / AFFECTED_SKILL / "SKILL.md").read_text(encoding="utf-8")
    assert rendered.count(_WIDTH_SWEEP_REPO_PARAGRAPH) == 1
    assert rendered.count(_WIDTH_SWEEP_LANE_SENTENCE) == 1


# ---------------------------------------------------------------------------
# (d) Anchor guard
# ---------------------------------------------------------------------------


def test_missing_repo_anchor_raises(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Anchor drift in the bundled source is a renderer bug — loud failure."""
    from hyperresearch.core import opencode_skills as mod

    monkeypatch.setattr(mod, "_WIDTH_SWEEP_REPO_ANCHOR", "not-the-real-anchor-xyz")
    with pytest.raises(Exception, match="anchor"):
        render_skills(tmp_path / "skills", PROFILE, repo_lane=True)


# ---------------------------------------------------------------------------
# (e) Install threading
# ---------------------------------------------------------------------------


def _install_vault(tmp_path: Path, *, repo_source_lane: bool) -> Path:
    from hyperresearch.core.vault import Vault

    vault = Vault.init(tmp_path, name="t")
    vault.config.web_repo_source_lane = repo_source_lane
    vault.config.save(vault.config_path)
    return tmp_path


def test_install_bakes_paragraph_when_flag_on(tmp_path: Path) -> None:
    root = _install_vault(tmp_path, repo_source_lane=True)
    result = runner.invoke(app, ["install", str(root), "--json"])
    assert result.exit_code == 0, result.output
    rendered = (
        root / ".opencode" / "skills" / AFFECTED_SKILL / "SKILL.md"
    ).read_text(encoding="utf-8")
    assert _WIDTH_SWEEP_REPO_PARAGRAPH in rendered


def test_install_leaves_golden_clean_when_flag_off(tmp_path: Path) -> None:
    root = _install_vault(tmp_path, repo_source_lane=False)
    result = runner.invoke(app, ["install", str(root), "--json"])
    assert result.exit_code == 0, result.output
    rendered = (
        root / ".opencode" / "skills" / AFFECTED_SKILL / "SKILL.md"
    ).read_text(encoding="utf-8")
    assert _WIDTH_SWEEP_REPO_PARAGRAPH not in rendered
    golden = SKILL_GOLDENS_DIR / f"{AFFECTED_SKILL}.md"
    assert rendered == golden.read_text(encoding="utf-8")


def test_install_profile_overlay_enables_lane(tmp_path: Path) -> None:
    from hyperresearch.core.vault import Vault

    vault = Vault.init(tmp_path, name="t")
    vault.config_path.write_text(
        vault.config_path.read_text()
        + '\n[profile.repoheavy]\nextends = "full"\nrepo_source_lane = true\n'
    )
    vault.config.pipeline_profile = "repoheavy"
    vault.config.save(vault.config_path)

    result = runner.invoke(app, ["install", str(tmp_path), "--json"])
    assert result.exit_code == 0, result.output
    rendered = (
        tmp_path / ".opencode" / "skills" / AFFECTED_SKILL / "SKILL.md"
    ).read_text(encoding="utf-8")
    assert _WIDTH_SWEEP_REPO_PARAGRAPH in rendered


# ---------------------------------------------------------------------------
# Fixture maintenance helper
# ---------------------------------------------------------------------------


def _freeze_repo_lane_golden(tmp_path: Path) -> None:
    """Regenerate the lane-on golden (run manually; not a test)."""
    skills_dir = _render(tmp_path, repo_lane=True)
    REPO_LANE_ON_GOLDENS_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy(
        skills_dir / AFFECTED_SKILL / "SKILL.md",
        REPO_LANE_ON_GOLDENS_DIR / f"{AFFECTED_SKILL}.md",
    )
    print(f"frozen -> {REPO_LANE_ON_GOLDENS_DIR / (AFFECTED_SKILL + '.md')}")


if __name__ == "__main__":  # pragma: no cover
    _freeze_repo_lane_golden(Path(".").resolve())
